print('======[BOSS DEFEATED]======')
crystals = int(input('How many crystals it dropped?'))
print(f'Energy Crystals: {crystals}')
print('=[Summary]=')
print('Captain: {}'.format(crystals%3))
print('Member 1: {}'.format(crystals/3))
print('Member 2: {}'.format(crystals/3))
print('Member 3: {}'.format(crystals/3))
print('===========')